camera:
  enabled: true
  device: /dev/video0
  width: 1280
  height: 720
  fps: 60
  pixel_format: MJPG
  test_image: ''
  reconnect_delay_ms: 1000
  calibration:
    image_to_capture_homography:
    - 0.0
    - -1.5
    - 1200.0
    - 1.2
    - 0.0
    - -768.0
    - 0.0
    - 0.0
    - 1.0
    roller_balance:
      roi_xyxy:
      - 28.64
      - 301.4
      - 1240.18
      - 360.23
      center_x_px: 639.81
      mm_per_pixel: 0.20635
      axis_direction: 1
